name: Publish Mod

# Run when a new release is... released
on:
  release:
    types: [published]
   

  workflow_dispatch:

jobs:
  main:
    name: ''
    uses: undorn/actions-workflows/.github/workflows/publish-modpack.yaml@main
    with:
      team: Undorn
      community: valheim
    secrets: inherit
