name: Publish Mod

# Run when a new release is... released
on:
  release:
    types: [published]

  push:
    paths-ignore:
      - .gitignore
      - ".github/**"
      - README.md

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    name: ''
    uses: undorn/actions-workflows/.github/workflows/publish-modpack.yaml@main
    with:
      team: Undorn
      community: valheim
    secrets: inherit
